# 1.Listas, Tuplas e Strings

In [7]:
conjunto = [1,2,3,4]

In [9]:
dir(conjunto)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [11]:
conjunto.append(5)

In [12]:
conjunto

[1, 2, 3, 4, 5]

In [21]:
tupla_numeros= (1,2,3,3)

In [14]:
tupla_numeros.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [16]:
conjunto[0]=7

In [17]:
conjunto

[7, 2, 3, 4, 5]

In [18]:
tupla_numeros[0]

1

In [22]:
tupla_numeros[0]=7

TypeError: 'tuple' object does not support item assignment

In [23]:
tupla_numeros

(1, 2, 3, 3)

In [24]:
palavra='Palmeiras'

In [26]:
dir(palavra)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [30]:
dicionario = {1:"São Paulo",2:'Grêmio'}

In [29]:
dicionario[2]

'Grêmio'

In [31]:
[1,2,3]+[5,6]

[1, 2, 3, 5, 6]

In [32]:
'Água'+'Doce'

'ÁguaDoce'

# 2.Loops

In [33]:
for numero in [1,2,4]:
    print(numero)
print('FIM')

1
2
4
FIM


In [34]:
conjunto

[7, 2, 3, 4, 5]

In [36]:
somado =[]
for numero in conjunto:
    somado.append(numero+1)
print(somado)
print('FIM')

[8, 3, 4, 5, 6]
FIM


In [37]:
somado = [numero+1 for numero in conjunto]

In [38]:
somado

[8, 3, 4, 5, 6]

# 3. IF e ELSE

In [45]:
somado =[]
for numero in conjunto:
    if numero % 2 == 0:
        print(numero+1)
    elif numero <= 5:
        print('É impar {}!'.format(numero))
print('FIM')

3
É impar 3!
5
É impar 5!
FIM


In [42]:
conjunto

[7, 2, 3, 4, 5]

# 4. Funções

In [49]:
def soma(x,y):
    'Soma dois Numeros'
    return x+y

In [47]:
soma(4,5)

9

In [48]:
dir(soma)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [51]:
lista_funcoes = [soma,soma]

In [52]:
lista_funcoes

[<function __main__.soma(x, y)>, <function __main__.soma(x, y)>]

# 5. Classes

In [67]:
class Animal:
    def respirar(self):
        print('Esse animal respira!')

class Cachorro(Animal):
    def __init__(self,nome,peso):
        
        self.nome = nome
        self.peso = peso
    
    def latir(self):
        print('Au')

In [68]:
cachorro_A = Cachorro('Scooby',50)

In [57]:
cachorro_A.nome

'Scooby'

In [58]:
cachorro_A.peso

50

In [66]:
cachorro_A.latir()

Au


In [69]:
dir(cachorro_A)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'latir',
 'nome',
 'peso',
 'respirar']

In [70]:
cachorro_A.respirar()

Esse animal respira!


# 5.Imports

In [71]:
import numpy as np

In [72]:
np.array([1,2,3])

array([1, 2, 3])

In [73]:
np.array([1,2,3]) +np.array([2,3,4])

array([3, 5, 7])

In [76]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [77]:
a+b

array([3, 5, 7])

In [78]:
a*b

array([ 2,  6, 12])

In [79]:
import pandas as pd

In [86]:
df = pd.DataFrame([[1,2],[2,3]],columns=['Coluna A','coluna B'])

In [89]:
df

Coluna A  coluna B
0         1         2
1         2         3

In [91]:
df.sum(axis=1)

0    3
1    5
dtype: int64

In [92]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex

# 7.ERROS

In [99]:
try:
    10 * (1/0)
except ZeroDivisionError as  err:
    print('Deu erro!')
    print(err)

Deu erro!
division by zero
