**Autor** : Hader Azzini

**e-mail**: hader.azzini@certsys.com.br

#  <a name="resumo"> RESUMO </a>

Este exercício tem o objetivo de permitir a prática dos conceitos fundamentais de python.

#  <a name="indice">  Índice </a>

* [Resumo](#resumo)
* [Índice](#indice)
* [Questões](#secao_1)
* [Resolução](#secao_2)
* [Conclusão](#conclusao)

#  <a name="secao_1"> Questões </a>
[Voltar ao índice](#indice)

1. Obtenha o *Patrimônio Líquido Total* da Apple nos ultimos 4 anos (linha **Total Stockholder Equity** do atributo balancesheet). Dica: para retornar uma linha no [pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html).
2. Gere um gráfico para o balanço patrimonial. Como gerar o [gráfico](https://plotly.com/python/line-and-scatter/).
3. Faça uma regressão linear para o balanço patrimonial e plot no gráfico.
4. Estime qual será o balanço patrimonial da apple para 2022.


### <span style="color:red">**Atenção! Antes de ver a resolução tente fazer o exercício primeiro, consulte apenas para verificar se está correto.**</span>

#  <a name="secao_2"> Resolução</a>
[Voltar ao índice](#indice)

## 1. Obtenha o *Patrimônio Líquido Total* da Apple nos ultimos 4 anos (linha **Total Stockholder Equity** do atributo balancesheet).

In [1]:
import yfinance as yf
ticker = "AAPL"
apple = yf.Ticker(ticker)

In [2]:
apple.balancesheet.loc['Total Stockholder Equity']


2021-09-25    6.309000e+10
2020-09-26    6.533900e+10
2019-09-28    9.048800e+10
2018-09-29    1.071470e+11
Name: Total Stockholder Equity, dtype: float64

In [12]:
patrimonio_liquido = apple.balancesheet.loc['Total Stockholder Equity']

## 2. Gere um gráfico para o balanço patrimonial.

In [4]:
import plotly.graph_objects as go

In [13]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=patrimonio_liquido.index,y=patrimonio_liquido.values))
fig.show()

## 3. Faça uma regressão linear para o balanço patrimonial e plot no gráfico.

In [49]:
from sklearn import linear_model
import numpy as np

In [15]:
regr = linear_model.LinearRegression()

In [20]:
X = patrimonio_liquido.index.year.values

In [31]:
X = X.reshape(-1,1)

In [24]:
y = patrimonio_liquido.values

In [32]:
y = y.reshape(-1,1)

In [33]:
regr.fit(X,y)

LinearRegression()

In [34]:
regr.coef_

array([[-1.5732e+10]])

In [35]:
regr.intercept_

array([3.185229e+13])

In [36]:
y_pred = regr.predict(X)

In [41]:
y_pred.reshape(1,-1)

array([[5.79180e+10, 7.36500e+10, 8.93820e+10, 1.05114e+11]])

In [45]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=patrimonio_liquido.index,y=patrimonio_liquido.values,name='Patrimônio Total Líquido'))
fig.add_trace(go.Scatter(x=patrimonio_liquido.index,y=y_pred.reshape(-1),name='Regressão Linear'))
fig.show()

## 4. Estime qual será o balanço patrimonial da apple para 2022.

In [54]:
patrimonio_2022 = regr.predict(np.array([2022]).reshape(1,-1))

In [55]:
patrimonio_2022

array([[4.2186e+10]])

In [56]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=patrimonio_liquido.index,y=patrimonio_liquido.values,name='Patrimônio Total Líquido'))
fig.add_trace(go.Scatter(x=patrimonio_liquido.index,y=y_pred.reshape(-1),name='Regressão Linear'))
fig.add_trace(go.Scatter(x=['2022-09-25'],y=patrimonio_2022.reshape(-1),name='Previsão'))
fig.show()

#  <a name="conclusao"> Conclusão </a>
[Voltar ao índice](#indice)

Neste exercicio conseguimos usar a regressão linear para estimar o patrimônio líquido da Apple